config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'relationships/create'
  get 'relationships/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'home_about'
  get "/search", to: 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
  resource :favorites, only: [:create,:destroy]
  resources :book_comments, only: [:create,:destroy]
end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      render :create
    else
      render 'books/show'
    end
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
    @book = Book.find(params[:book_id])
    render :create
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<div>
  <%= form_with model:[book,book_comment],local:false do |f| %>
    <%= f.text_area :comment,rows: '5',placeholder: "コメントをここに", class: "w-100" %>
    <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  <% end %>
</div>

app/views/book_comments/_index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user) do %>
          <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
      <td>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$(".comments-area").html("<%= j(render 'book_comments/index', book: @book, book_comment: @book_comment) %>");
<!--コメントフォームを空にする-->
$("textarea").val('');